export const TYPES = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    DECREMENT_5: 'DECREMENT_5',
    INCREMENT_5: 'INCREMENT_5',
    MULTIPLY: 'MULTIPLY',
    DIVIDE: 'DIVIDE',
    RESET: 'RESET'
}